# Generated by Django 4.0.4 on 2022-07-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pay_info_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='single_product_buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
