# Generated by Django 4.0.4 on 2022-07-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_buy_single_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay_info',
            name='BANKNAME',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='BANKTXNID',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='CHECKSUMHASH',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='CURRENCY',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='GATEWAYNAME',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='MID',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='ORDERID',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='PAYMENTMODE',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='RESPCODE',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='RESPMSG',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='STATUS',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='TXNAMOUNT',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='TXNDATE',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='TXNID',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='current_date_time',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='expiry_date_time',
        ),
        migrations.RemoveField(
            model_name='pay_info',
            name='message',
        ),
    ]
