# Generated by Django 4.0.4 on 2022-07-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_pay_info_bankname_remove_pay_info_banktxnid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
